### ISSUE TITLE
Hangs at Translating...

### ISSUE THREAD

**Issue by sheathompson** [MattDelmarter/missive-translate#3]
For some reason when I use this addon, it just hangs on translating and never goes anywhere.

**Comment by julesbsz** [comment]
Same for me... Have the following error :

translator.htm?key=[...] Uncaught TypeError: Cannot read properties of undefined (reading 'body')
    at showError (translator.htm?key=[...])
    at Object.success (translator.htm?key=[...])
    at u (jquery-3.3.1.min.js:2:27457)
    at Object.fireWith [as resolveWith] (jquery-3.3.1.min.js:2:28202)
    at k (jquery-3.3.1.min.js:2:77651)
    at HTMLScriptElement.n (jquery-3.3.1.min.js:2:80950)
    at HTMLScriptElement.dispatch (jquery-3.3.1.min.js:2:41772)
    at y.handle (jquery-3.3.1.min.js:2:39791)
